client:
    extends:
        file: ./client/client.yml
        service: client
    ports:
        - "8081:8080"
    volumes: 
        - ./client/src:/data/src
    environment:
        - CONFIGURATION=DEBUG

api:
    extends:
        file: ./api/api.yml
        service: api
    ports:
        - "8082:5000"
    volumes:
        - ./api/src:/data/src
    links:
        - db
        - mopidy
db:
    image: postgres

mopidy:
    build: ./mopidy
    expose:
        - "6680"
    privileged: true
