client:
    extends:
        file: ./client/client.yml
        service: client
    ports:
        - "8081:8080"
    volumes: 
        - ./client/src:/data/src
    environment:
        - CONFIGURATION=DEBUG
    links: 
        - logs

api:
    extends:
        file: ./api/api.yml
        service: api
    ports:
        - "8082:5000"
    volumes:
        - ./api/src:/data/src
    links:
        - db
        - mopidy
        - logs
    environment:
        - CONFIGURATION=DEBUG

service:
    extends:
        file: ./service/service.yml
        service: service
    volumes:
        - ./service/src:/data/src
    links:
       - api
       - logs
    environment:
       - CONFIGURATION=DEBUG

db:
    image: postgres

mopidy:
    build: ./mopidy
    expose:
        - "6680"
    privileged: true
    links:
        - logs

logs:
    image: maluuba/rtail-server
    ports:
        - "8083:8888"
    environment:
        - DEBUG=rtail:*
