client:
    build: ./client
    command: http-server /data/src -c-1 --cors
    ports:
        - "8081:8080"

api:
    build: ./api
    command: python /data/src/Server.py
    #command: gunicorn -w 2 -b 0.0.0.0:5000 Server:app
    working_dir: /data/src
    ports:
        - "8082:5000"
    links:
        - db
        - mopidy
db:
    image: postgres

mopidy:
    build: ./mopidy
    expose:
        - "6680"
    privileged: true
